services:
  backend-chinaloh:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - chinaloh-net

  frontend-chinaloh:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend-chinaloh
    restart: unless-stopped
    networks:
      - chinaloh-net

networks:
  chinaloh-net:
    driver: bridge
